# Generated by Django 5.0.3 on 2024-04-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
